meta_product_name: "Impact"
meta_title: "Impact - Be part of the change"
meta_description: "Make an impact with your actions"
meta_image: "impact-logo.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards