meta_product_name: "Impact"
meta_title: "Impact"
meta_description: "Be part of the change"
# meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards